# Generated by Django 5.1.15 on 2026-09-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='设施名称')),
                ('location', models.CharField(blank=True, default='', max_length=128, verbose_name='位置')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='说明')),
                ('status', models.CharField(choices=[('开放', '开放'), ('停用', '停用')], default='开放', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'facility',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FacilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='开放日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('start_dt', models.DateTimeField(verbose_name='开始时刻')),
                ('end_dt', models.DateTimeField(verbose_name='结束时刻')),
                ('is_open', models.BooleanField(default=True, verbose_name='是否开放预约')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='facility.facility', verbose_name='设施')),
            ],
            options={
                'db_table': 'facility_slot',
                'ordering': ['start_dt'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=32, verbose_name='租客姓名')),
                ('tenant_phone', models.CharField(max_length=20, verbose_name='租客手机号')),
                ('status', models.CharField(choices=[('待核销', '待核销'), ('已取消', '已取消'), ('已核销', '已核销'), ('已完成', '已完成'), ('爽约', '爽约')], default='待核销', max_length=10, verbose_name='状态')),
                ('voucher_code', models.CharField(max_length=12, unique=True, verbose_name='核销凭证号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预约时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='核销时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='使用结束时间')),
                ('no_show_at', models.DateTimeField(blank=True, null=True, verbose_name='爽约标记时间')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='facility.facility', verbose_name='设施')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='facility.facilityslot', verbose_name='时段')),
            ],
            options={
                'db_table': 'facility_reservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='facilityslot',
            index=models.Index(fields=['facility', 'date'], name='facility_sl_facilit_11f066_idx'),
        ),
        migrations.AddIndex(
            model_name='facilityslot',
            index=models.Index(fields=['start_dt'], name='facility_sl_start_d_8457a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['tenant_phone'], name='facility_re_tenant__70326f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['status'], name='facility_re_status_e82f81_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['voucher_code'], name='facility_re_voucher_8ff271_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('待核销', '已核销'))), fields=('facility', 'slot'), name='uniq_active_reservation_per_slot'),
        ),
    ]
